function y = apply_channel_filter(x,fs,lowHz,highHz)
%APPLY_CHANNEL_FILTER Controlled band-limiting/channel perturbation.

d=designfilt("bandpassiir", ...
    "FilterOrder",8, ...
    "HalfPowerFrequency1",lowHz, ...
    "HalfPowerFrequency2",highHz, ...
    "SampleRate",fs);

y=filtfilt(d,double(x(:)));
end
